init:
  goVersion: 1.22

pipeline:
  deploy:
    set_sdk:
      action: sdk.set
      target: $target
      sdk: go:${goVersion}

    install_dependencies:
      action: exec:run
      target: $target
      checkError: true
      env:
        appPath: ${appPath}
        goVersion: ${goVersion}
      commands:
        - bash ${appPath}/example/e2e/build-tensorflow-go/install-dependencies.sh
