init:
  target:
    URL: ssh://localhost/
    credentials: localhost
  appPath: $WorkingDirectory(../..)

pipeline:
  init:
    description: Initialize separate dependencies
    system:
      action: run
      request: '@system'
      tasks: '*'

  deps:
    deps:
      action: run
      request: '@deps'
      tasks: '*'

  build:
    build:
      action: run
      request: '@build'
      tasks: '*'
  stop:
    stop:
      action: run
      request: '@regression/app'
      tasks: stop

  test:
    action: run
    description: run regression test
    request: '@regression/regression'
