init:
  target:
    URL: ssh://localhost/
    credentials: localhost
  appPath: $WorkingDirectory(../..)


pipeline:
  init:
    description: initialise test (docker,database,build app)
    system:
      action: run
      request: '@system'
      tasks: '*'

    build:
      action: run
      request: '@build'
      tasks: '*'


  test:
    action: run
    description: run regression test
    request: '@regression/regression'
