init:
  modelRepo: ${appPath}/example/e2e/data/triton_model_repository

pipeline:
  stop:
    mly_aero:
      action: docker:stop
      names:
        - mly_aero
    mly_triton:
      action: docker:stop
      names:
        - mly_triton
    mly_triton_grpc_explicit:
      action: docker:stop
      names:
        - mly_triton_grpc_explicit

  copyModels:
    action: exec:run
    target: $target
    checkError: true
    commands:
      - mkdir -p ${modelRepo}/sli_1/1/model.savedmodel
      - cp -r ${appPath}/example/model/string_lookups_int_model/* ${modelRepo}/sli_1/1/model.savedmodel
      - mkdir -p ${modelRepo}/sli_2/1/model.savedmodel
      - cp -r ${appPath}/example/model/string_lookups_int_model/* ${modelRepo}/sli_2/1/model.savedmodel
      - mkdir -p ${modelRepo}/sli_exp/1/model.savedmodel
      - cp -r ${appPath}/example/model/string_lookups_int_model/* ${modelRepo}/sli_exp/1/model.savedmodel
      - mkdir -p ${modelRepo}/sli_local/1/model.savedmodel
      - cp -r ${appPath}/example/model/string_lookups_int_model/* ${modelRepo}/sli_local/1/model.savedmodel
      - mkdir -p ${modelRepo}/r2/1/model.savedmodel
      - cp -r ${appPath}/example/model/r2_output_model/* ${modelRepo}/r2/1/model.savedmodel
      - mkdir -p ${modelRepo}/ko/1/model.savedmodel
      - cp -r ${appPath}/example/model/keyed_out_model/* ${modelRepo}/ko/1/model.savedmodel

  start:
    aerospike:
      action: docker:run
      image: 'aerospike/aerospike-server:3.16.0.6'
      name: mly_aero
      ports:
        3000: 3000
        3001: 3001
        3002: 3002

    triton:
      action: docker:run
      name: mly_triton
      image: 'nvcr.io/nvidia/tritonserver:25.02-py3'
      platform: linux/arm64
      port: "8070/tcp"
      ports:
        8070: 8000
        8071: 8001
        8072: 8002
      mount:
        ${modelRepo}: /models
      cmd:
        - tritonserver
        - --model-repository=/models
        - --backend-config=tensorflow,default-max-batch-size=32
      entrypoint:
        - /opt/nvidia/nvidia_entrypoint.sh

    triton_grpc_explicit:
      action: docker:run
      name: mly_triton_grpc_explicit
      image: 'nvcr.io/nvidia/tritonserver:25.02-py3'
      platform: linux/arm64
      port: "8101/tcp"
      ports:
        8100: 8000
        8101: 8001
        8102: 8002
      mount:
        ${modelRepo}: /models
      cmd:
        - tritonserver
        - --model-repository=/models
        - --model-control-mode=explicit
        - --backend-config=tensorflow,default-max-batch-size=32
      entrypoint:
        - /opt/nvidia/nvidia_entrypoint.sh