init:
  parentPath: $parent.path

pipeline:
  test:
    action: http/runner:send
    requests:
      - Method: POST
        URL: http://127.0.0.1:8086/v1/api/model/sli_triton/eval
        JSONBody: {"batch_size": 0,  "cache_key": "test-a-a-10",  "sa": "a",  "sl":"a",  "aux": "test"}
        Expect:
          Code: 200
          Body: $LoadJSON('${parent.path}/expect.json')
