init:
  parentPath: $parent.path

pipeline:
  test:
    action: exec:run
    target: $target
    checkError: true
    commands:
      - /tmp/e2e/mlyc -m fli -a 'fl|float32:1.0005;sl:a'
      - /tmp/e2e/mlyc -m fli -a 'fl|float32:1.0008;sl:a'

  assert:
    action: validator:assert
    init:
      actual: $AsJSON($test.Cmd[0].Stdout)
    actual: $actual
    expect: $LoadJSON('${parentPath}/expect.json')

  assertCache:
    action: validator:assert
    init:
      actual: $AsJSON($test.Cmd[1].Stdout)
    actual: $actual
    expect: $LoadJSON('${parentPath}/expect-cache.json')

