Endpoint:
  Port: 8086

models:
  - id: sli
    url: ${appPath}/example/model/string_lookups_int_model
    useDict: true
    transformer: sls
    datastore: sls
    inputs:
      - name: sa
      - name: sl
      - name: aux
        auxiliary: true

connections:
  - id: localL1
    hostnames: localhost
    port: 3000
    timeout: null

datastores:
  - id: sls
    cache:
      sizeMb: 128
    connection: localL1
    namespace: test
    dataset: sls
    storable: sls
    timeToLiveMs: 3600000

