init:
  parentPath: $parent.path

pipeline:
  test:
    action: exec:run
    target: $target
    commands:
      - /tmp/e2e/mlyc -m vec -a 'tv:a;sl:b'
      - /tmp/e2e/mlyc -m vec -a 'extra:c;tv:a;sl:b'
      - /tmp/e2e/mlyc -m vec -a 'tv|int:0;sl:b'
      - curl -s localhost:8086/v1/api/metric/operation/vecPerf

  assertMetrics:
    action: validator:assert
    init:
      actual: $AsJSON($test.Cmd[3].Stdout)
    actual: $actual
    expect: $LoadJSON('${parentPath}/metrics.json')

