init:
  parentPath: $parent.path

pipeline:
  test:
    action: exec:run
    target: $target
    commands:
      - curl -s localhost:8086/v1/api/health

  assertMetrics:
    action: validator:assert
    init:
      actual: $AsJSON($test.Cmd[0].Stdout)
    actual: $actual
    expect: $LoadJSON('${parentPath}/metrics.json')

