init:
  parentPath: $parent.path

pipeline:
  test:
    action: exec:run
    target: $target
    commands:
      - curl -s localhost:8086/v1/api/health

  assertMetrics:
    action: validator:assert
    actual: $AsJSON($test.Cmd[0].Stdout)
    expect: |
      {
        "sli": 1
      }