init:
  parentPath: $parent.path

pipeline:
  test:
    action: exec:run
    target: $target
    checkError: true
    commands:
      - /tmp/e2e/mlyc -m ll -a 'lookuplayer_input|int:0'
      - /tmp/e2e/mlyc -m ko -a 'i|int:0'

  assert:
    action: validator:assert
    init:
      actual: $AsJSON($test.Cmd[0].Stdout)
      expect: expect-ll
    actual: $actual
    expect: $LoadJSON('${parentPath}/${expect}.json')

  assertCache:
    action: validator:assert
    init:
      actual: $AsJSON($test.Cmd[1].Stdout)
      expect: expect-ko
    actual: $actual
    expect: $LoadJSON('${parentPath}/${expect}.json')
