init:
  parentPath: $parent.path

pipeline:
  test:
    action: exec:run
    target: $target
    checkError: true
    commands:
      - /tmp/e2e/mlyc -m=vec -a 'tv:a b c;sl:a;aux:1'
      - /tmp/e2e/mlyc -m=vec -a 'tv:a b c;sl:a;aux:1'

  assert:
    action: validator:assert
    init:
      actual: $AsJSON($test.Cmd[0].Stdout)
      expect: expect
    actual: $actual
    expect: $LoadJSON('${parentPath}/${expect}.json')

  assertCache:
    action: validator:assert
    init:
      actual: $AsJSON($test.Cmd[1].Stdout)
      expect: expect-cache
    actual: $actual
    expect: $LoadJSON('${parentPath}/${expect}.json')
