pipeline:
  copyConfig:
    action: storage:copy
    expand: true
    source:
      URL: ${appPath}/example/server/etc/config.yaml
    dest:
      URL: /tmp/e2e/config.yaml

  stop:
    action: process:stop
    target: $target
    input: mly-endly

  start:
    action: process:start
    target: $target
    directory: /tmp/e2e
    checkError: true
    immuneToHangups: true
    command: ./mly-endly -c=/tmp/e2e/config.yaml
    env:
      DEBUG: 'true'
      DYLD_LIBRARY_PATH: /usr/local/lib
      LD_LIBRARY_PATH: /usr/local/lib
  
  waitForBoot:
    action: exec:run
    target: $target
    checkError: true
    commands:
      - bash ${appPath}/example/e2e/check-port.sh localhost:8086 30
    
