pipeline:

  copyConfig:
    action: storage:copy
    expand: true
    source:
      URL: ${appPath}/example/server/etc/config.yaml
    dest:
      URL: /tmp/e2e/config.yaml

  stop:
    action: process:stop
    target: $target
    input: datly

  start:
    action: process:start
    sleepTimeMs: 3000
    target: $target
    directory: /tmp/e2e
    checkError: true
    immuneToHangups: true
    env:
      TEST: 1
    command: ./mly -c=/tmp/e2e/config.yaml