
pipeline:

  reset_aero:
    init:
      action: dsunit:init
      recreate: true
      datastore: aero
      config:
        driverName: aerospike
        descriptor: tcp([host]:3000)/test
        parameters:
          dbname: aero
          namespace: test
          host: 127.0.0.1
          port: 3000
          keyColumnName: id
          excludedColumns: id

    populate:
      action: dsunit:prepare
      datastore: aero
      URL: ${appPath}/example/e2e/regression/reset
