init:
  parentPath: $parent.path

pipeline:
  test:
    action: exec:run
    target: $target
    checkError: true
    commands:
      - /tmp/e2e/mlyc -m sli -a 'sa:a;sl:a;aux:test;kf:k'
      - /tmp/e2e/mlyc -m slf -s slft_batch -a 'sa:a,b;sl:b;aux:test'
      - /tmp/e2e/mlyc -m slf --maker=slft_batch -a 'sa:b;sl:b;aux:test'

  assert:
    action: validator:assert
    init:
      actual: $AsJSON($test.Cmd[0].Stdout)
    actual: $actual
    expect: |
      {
        "data": {
          "D": {
            "expand": 25
          }
        }
      }

  assertStorable:
    action: validator:assert
    init:
      actual: $AsJSON($test.Cmd[1].Stdout)
    actual: $actual
    expect: |
      {
        "data": [
          {
            "Class": "five"
          },
          {
            "Class": "five"
          }
        ]
      }

  assertCustom:
    action: validator:assert
    init:
      actual: $AsJSON($test.Cmd[2].Stdout)
    actual: $actual
    expect: |
      {
        "data": {
          "Class": "five"
        }
      }
