Endpoint:
  Port: 8086

models:
  - id: sli
    url: ${appPath}/example/model/string_lookups_int_model
    useDict: true
    debug: false
    datastore: sli
    inputs:
      - name: sa
      - name: sl
      - name: aux
        auxiliary: true
    test:
      test: true

  - id: slf
    url: ${appPath}/example/model/string_lookups_float_model
    useDict: true
    debug: false
    datastore: slf
    transformer: slft
    inputs:
      - name: sa
      - name: sl
      - name: aux
        auxiliary: true
    test:
      singleBatch: true

  - id: fli
    url: ${appPath}/example/model/float_input_int_model
    useDict: true
    debug: false
    datastore: fli
    inputs:
      - name: fl
        precision: 4

  - id: flinc
    url: ${appPath}/example/model/float_input_int_model
    useDict: false
    debug: false
    datastore: fli

  - id: vec
    url: ${appPath}/example/model/vectorization_int_model
    useDict: true
    debug: false
    datastore: vec
    inputs:
      - name: tv
        wildcard: true
      - name: sl
      - name: aux
        auxiliary: true
    test:
      test: true

  - id: ll
    url: ${appPath}/example/model/broken_case_v0_5_0_model
    useDict: false
    debug: false
    inputs:
      - name: lookuplayer_input
    test:
      test: true

  - id: ko
    url: ${appPath}/example/model/keyed_out_model
    useDict: false
    debug: false
    test:
      singleBatch: true

  - id: slow
    url: ${appPath}/example/model/slow_model
    useDict: false
    debug: false
    test:
      singleBatch: true

connections:
  - id: localL1
    hostnames: localhost
    port: 3000
    timeout: 300

datastores:
  - id: sli
    connection: localL1
    namespace: test
    dataset: sli
    timeToLiveMs: 30000

  - id: slf
    connection: localL1
    namespace: test
    dataset: slf
    timeToLiveMs: 30000

  - id: vec
    connection: localL1
    namespace: test
    dataset: vec
    timeToLiveMs: 30000

  - id: fli
    connection: localL1
    namespace: test
    dataset: fli
    timeToLiveMs: 30000
