init:
  parentPath: $parent.path

pipeline:
  test:
    action: exec:run
    target: $target
    checkError: true
    commands:
      - /tmp/e2e/mlyc -m sli -a 'sa:a;sl:a;aux:test;kf:k'
      - /tmp/e2e/mlyc -m sli -a 'sa:a;sl:a;aux:test;kf:k'

  assert:
    action: validator:assert
    init:
      actual: $AsJSON($test.Cmd[0].Stdout)
    actual: $actual
    expect: $LoadJSON('${parentPath}/expect.json')

  assertCache:
    action: validator:assert
    init:
      actual: $AsJSON($test.Cmd[1].Stdout)
    actual: $actual
    expect: $LoadJSON('${parentPath}/expect-cached.json')
